In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

In [2]:
#df = pd.read_csv('file_location/file_name')
df = pd.read_csv('Complete_aljazeera.csv')

In [3]:
#Remove Digits

df = df[~df.word.str.contains("\\d")]

In [4]:
#Sort by decending frequency

df = df.sort_values('freq', ascending=False)
df.head(20)

         Unnamed: 0       word  freq      date
1372295           0  president  1548  20191120
129595            0     people  1507  20220102
1148570           0     people  1471  20200403
1146920           0     people  1469  20200404
648928            0   military  1448  20210201
1162805           0     people  1440  20200325
35369             0    ukraine  1430  20220224
848447            0  president  1420  20201002
1324785           0  president  1415  20191218
1158138           0     people  1414  20200328
679404            0  president  1408  20210113
1167455           0     people  1406  20200322
1151765           2     people  1404  20200401
1143628           0     people  1398  20200406
1169079           0     people  1387  20200321
1153365           1     people  1371  20200331
1145294           0     people  1369  20200405
1150194           0     people  1357  20200402
360102            0     people  1356  20210820
356744            0     people  1349  20210822

In [5]:
#Remove General Phrases
#You can choose whatever words you want to from the .head(20) above

df = df[~df.word.str.contains("people")]
df = df[~df.word.str.contains("day")]
df = df[~df.word.str.contains("continue")]
df = df[~df.word.str.contains("day")]
df = df[~df.word.str.contains("city")]

In [6]:
#Remove Dups
df = df.drop_duplicates("word")

In [17]:
#combine similar word frequency

corona = df[df.word.str.contains('corona')]
covid = df[df.word.str.contains('covid')]
corona_freq = corona.freq.sum() + covid.freq.sum()

vaccine = df[df.word.str.contains('vaccin')]
vaccine_freq = vaccine.freq.sum()

In [8]:
#slice terms and adjust freq

temp_corona = df.loc[df['word'] == 'corona']
temp_corona.freq = corona_freq

df = df[~df.word.str.contains("corona")]
df = df[~df.word.str.contains("covid")]

temp_vaccine = df.loc[df['word'] == 'vaccin']
temp_vaccine.freq = vaccine_freq

df = df[~df.word.str.contains("vaccin")]

C:\Users\Casey\anaconda3\lib\site-packages\pandas\core\generic.py:5494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [9]:
#Append Slice

df = df.append(temp_corona)
df = df.append(temp_vaccine)
print(df[df.word.str.contains('corona')])
print(df[df.word.str.contains('vaccin')])

         Unnamed: 0    word  freq      date
1159853         125  corona   752  20200327
Empty DataFrame
Columns: [Unnamed: 0, word, freq, date]
Index: []

In [10]:
#Sort again

df = df.sort_values('freq', ascending=False)

In [11]:
df.head(30)

         Unnamed: 0         word  freq      date
1372295           0    president  1548  20191120
648928            0     military  1448  20210201
35369             0      ukraine  1430  20220224
1289842           0         iran  1279  20200108
35373             4      russian  1217  20220224
794178            1        trump  1202  20201104
1297898           9         u.s.  1174  20200103
745239           11         know  1115  20201204
35370             1       russia  1101  20220224
794180            3        biden  1086  20201104
1052715           0       police  1055  20200601
1297949          61         iraq   975  20200103
493399            1         gaza   946  20210512
794208           31        votes   922  20201104
1420305           0   government   910  20191022
368044            2      taliban   891  20210815
491845            2       israel   836  20210513
493398            0      israeli   828  20210512
794177            0       states   795  20201104
794188           11        state   771  20201104
1324786           1  impeachment   771  20191218
1159853         125       corona   752  20200327
283620            1     facebook   743  20211005
980637            0        china   737  20200714
7                 7          war   727  20220317
791199            1     election   721  20201106
794186            9          joe   711  20201104
1324790           5        house   708  20191218
1298138         301        money   689  20200103
22432            54      nuclear   673  20220304

In [12]:
# Output the data to excel for wordcloud
#Copy of Aditya Code
master_df.to_csv('path to store file/filename.csv', sep=',')

NameError: name 'master_df' is not defined